#!/bin/bash
#
# Copyright 2011 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

get_barcode() {
  echo "Please type or wand barcode"
  read barcode
  isbn=${barcode:0:13}
  xdg-open "http://books.google.com/books?vid=isbn${barcode}" 2> /dev/null
}

scan() {
  echo "finding scanners"
  local SCANNERS=$(scanimage -L)
  if [ $(echo "$SCANNERS" | wc -l) != 2 ]; 
  then
    echo "Error. I need two scanbars to proceed, and all I have is:"
    echo "$SCANNERS"
    exit 1
  fi

  local S1=$(echo "$SCANNERS" | grep "LiDE 110" | cut -f2 -d'`' | cut -f1 -d"'")
  local S2=$(echo "$SCANNERS" | grep "LiDE 210" | cut -f2 -d'`' | cut -f1 -d"'")

  echo "testing scanners"
  # red = left, bluish = right, just like 3D glasses
  scanimage -d "$S1" --color-filter=Red > /dev/null &
  sleep 2
  scanimage -d "$S2" --color-filter=Blue > /dev/null
  wait

  get_barcode

  # Driver hacked such that -y 111 means "scan as long as you can"
  local ARGS="-y 111 --mode=gray"

  ./forever.py scanimage -d $S1 $ARGS $@ |\
    ./meter.py | ./wobble.py | ./split.py 0 $barcode | ./viewer.py > /dev/null &
  sleep 2
  ./forever.py scanimage -d $S2 $ARGS $@ |\
    ./wobble.py | ./split.py 1 $barcode | ./viewer.py > /dev/null &
}

# Catch INT signal from Ctrl-C
trap "killall -SIGTERM scanimage; exit 0" INT

scan $@
wait

