#!/bin/bash
#
# Copyright 2011 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

scan() {
  local SCANNERS=$(scanimage -L)
  if [ $(echo "$SCANNERS" | wc -l) != 2 ]; 
  then
    echo "Error. I need two scanbars to proceed, and all I have is:"
    echo "$SCANNERS"
    exit 1
  fi

  local S1=$(echo "$SCANNERS" | head -1 | cut -f2 -d'`' | cut -f1 -d"'")
  local S2=$(echo "$SCANNERS" | tail -1 | cut -f2 -d'`' | cut -f1 -d"'")

  ARGS="--clear-calibration --resolution 600"

  scanimage -d $S1 -y 111 $CAL --mode=color | tee /var/tmp/a |\
    ./viewer.py 8 | ./wobble.py | ./split.py > /dev/null &

  scanimage -d $S2 -y 111 $CAL --mode=color | tee /var/tmp/b |\
    ./viewer.py 8 | ./wobble.py | ./split.py 1 > /dev/null &
}

scan
wait

