#!/bin/bash
#
# Copyright 2011 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

get_barcode() {
  while [ "${barcode:0:3}" != "978" ]; do
    echo "Prepare for calibration then wand ISBN"
    read barcode
  done
  isbn=${barcode:0:13}
  xdg-open "http://books.google.com/books?vid=isbn${barcode}" 2> /dev/null
}

scan() {
  local SCANNERS=$(scanimage -L)
  if [ $(echo "$SCANNERS" | wc -l) != 2 ]; 
  then
    echo "Error. I need two scanbars to proceed, and all I have is:"
    echo "$SCANNERS"
    exit 1
  fi

  local S1=$(echo "$SCANNERS" | head -1 | cut -f2 -d'`' | cut -f1 -d"'")
  local S2=$(echo "$SCANNERS" | tail -1 | cut -f2 -d'`' | cut -f1 -d"'")

  # red = left, bluish = right, just like 3D glasses
  scanimage -d $S1 --clear-calibration --color-filter=Red > /dev/null &
  scanimage -d $S2 --clear-calibration --color-filter=Blue > /dev/null
  wait

  get_barcode

  # Driver hacked such that -y 111 means "scan as long as you can"
  local ARGS="-y 111 --mode=color"

  ./forever.py scanimage -d $S1 $ARGS $@ |\
    ./meter.py | ./wobble.py | ./split.py 0 $barcode | ./viewer.py > /dev/null &

  ./forever.py scanimage -d $S2 $ARGS $@ |\
    ./wobble.py | ./split.py 1 $barcode | ./viewer.py > /dev/null &

  sleep 5
  echo -n "Calibration complete. Begin scanning."
}

scan $@
wait

